const verify = () => {
    const m_g = "R1B5Rnh2WjRwRElzb2pMZ1FZVFBYMWRWT0NLQ2NqWEdBT2Q1WVVOOFdmQnJkVVRHOkFJU1BsaW1YcHVHMDQzWHZLNlgyYzFoeTNXMzB0R1VPTVFnUmtFdktoWUZOUEdXUlB6bTVYVFYzMkFiS1pEVG4="
    const nm_g = "R1B5Rnh2WjRwRElzb2pMZ1FZVFBYMWRWT0NLQ2NqWEdBT2Q1WVVOOFdmQnJkVVRHOkFJU1BsaW1YcHVHMDQzWHZLNlgyYzFoeTNXMzB0R1VPTVFnUmtFdktoWUZOUEdXUlB6bTVYVFYzMkFiS1pEVG4="

    console.log(m_g === nm_g)
}

verify()


```

```